### PR TITLE
MetaData import/export as ComicBookInfo Format, added http://readdcentertainment.com/ to manifest

### PR DESCRIPTION
**Pull request by Cyberman-tM**
Modified zip.js to allow placement of ZIP header comments.
Added code to read metadata (credits, name, series) from LIST view
Metadata is saved in this format: https://code.google.com/p/comicbookinfo/wiki/Example
Tested against ComicTagger and Calibre. (Note: Calibre doesn't differentiate persons - author and penciller are both authors to calibre, nothing I can do, except maybe write a plugin for Calibre...)

Added DC to manifest, same reader tech - I actually tested mostly using their page (less comics).

Note: credits may need to check for additional synonyms, comixology isn't consistent in their use.

I'm unsure how to proceed with Calibre WRT credits. All persons are authors to it - having cover, art, pencils etc... separate is nice, but weird if they're suddenly all authors in Calibre. Maybe add a setting "export for calibre" where anything but actual writer is supressed?
Idea: specify by setting which metadata to export?

Unrelated Calibre bug: "issue" and "volume" are used synonymously, and having only issue causes abortion of metadata import, so currently both are filled with the same value. Shouldn't be any trouble, I think, and it's better to have some metadata than none at all.

### CODE REVIEW

**Comment by Cortys** [comment]
Great! Seems to work fine.

I think these things should still be resolved though:
- As far as I can tell you are always storing the metadata as standard JSON. If that's correct, I'd prefer a `JSON.stringify` based implementation because it results in easier maintainable code and is battle-proven (regarding special character edge cases and whatnot).
- In version 2.2.0 I moved the scan-button-generation-logic to the `show` method to make it possible to display multiple scan buttons for one comic at the same time (necessary in the new Smart Lists view). I'd be nice if the metadata scan happened in `show` instead of the constructor. This would make it possible to open the page in a "wrong" viewing mode and still get the metadata as soon as you switch to the right one.

If don't have enough time for this, please tell me and I'll give it a shot as well.

**Comment by Cyberman-tM** [comment]
I'll take a look and let you know when I encounter problems.

**Comment by Cyberman-tM** [comment]
BTW, is there an easy way to split the metadata object into its own file? It would be better to maintain that way.

**Comment by Cortys** [comment]
Sure. You can add a new file in the manifest: https://github.com/Cortys/comixology-backup/blob/master/source/manifest.json#L44 Just make sure, that the MetaData class is set in the global scope, so that myBooks.js can access it.

**Comment by Cyberman-tM** [comment]
OK, I think I have everything - take a look please.
I've moved the MetaData coding into a file of it's own, including the part that actually extracts the data. So all that remains in myBooks.js are the definition of the metaData object and the call to the extraction method.

Note: the metadata in the CBZ file IS correct, but right now Calibre won't be able to read it, due to the previously mentioned bug in Calibre. AFAIK they've fixed it, so the next patch should solve that.

**Comment by Cortys** [comment]
Thanks a lot! I'll try to get it rolled out today.

**Pull request merged**
