### PR TITLE
Added toast content to Comixology-Backup

### PR DESCRIPTION
**Pull request by EricPonvelle**
Per Issue #43, I added a Toast message that will pop up every time a change is made to the fields.

### CODE REVIEW

**Comment by Cortys** [comment]
Great work!

Just three minor things:
- In my opinion each toast is visible too long. When changing multiple settings, the toasts pile up fairly quickly.
- I think, that the height of a toast is a bit too much as well. I do not know if this is intentional or simply the default config. If it is the former, I'm of course willing to discuss this.
- Could you delete all files, that are part of the toastr framework and not directly depended upon (e. g. the changelog, unit tests, readme, demo etc.).

After these points are addressed, I'll happily merge this in. 

Thanks!

**Comment by EricPonvelle** [comment]
Ahh easy fixes. I'll fix them when I get home. Thanks for the feedback.

**Comment by EricPonvelle** [comment]
I updated the files with fixes. I removed (and tested after removing) all the extra files. It still works.

I decreased the hold duration from 5000 (ms, I guess) to 500. It was still possible to stack notifications, but I was basically trying to stack them. It wasn't something that'll be done easily, but you still can see the saved changes. If you want to decrease or increase the time whenever you want, under toast.js, go to the getDefaults function and edit this value:

"timeOut: 400, // Set timeOut and extendedTimeOut to 0 to make it sticky"

Finally, I removed the padding off the toast container class in the toastr.css file. That reduced the size of the toast a lot. Not sure if you want it even smaller.

Let me know if this helps!

**Comment by Cortys** [comment]
Chrome won't load the extension now.

Looks like you accidentally removed the zip.js library instead of the toastr files: `package.json`, `karma.conf.js`, `gulpfile.js`, jquery (which is imported but never used if I'm not mistaken) and various other toastr related build files are still there.

`toastr.min.js` and `toastr.min.css` or their unminified versions (minification does not really matter since all files are local) is all that's needed (https://github.com/CodeSeven/toastr#minified) according to the toastr docs.

**Comment by EricPonvelle** [comment]
jquery is called in toastr.js. I tested the extension with jquery and without, and it has to be included.

I removed everything except toastr.js, toastr.css, and jquery.

**Comment by Cortys** [comment]
Thanks a lot for your work!

I'll try to get the next release done this weekend.

**Pull request merged**
